# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20161117_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.TextField(blank=True, max_length=500, verbose_name='description'),
        ),
    ]
