# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0004_auto_20161117_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='priv',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', through='profile.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorship',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Group'),
        ),
        migrations.AddField(
            model_name='creatorship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='creators',
            field=models.ManyToManyField(related_name='creators', through='profile.Creatorship', to=settings.AUTH_USER_MODEL),
        ),
    ]
