# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20161205_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
