# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_profile_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='priv',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
    ]
