# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20161127_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='name',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='rfile',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
