# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_merge_20161127_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='rfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
