# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20161127_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
