# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='rhash',
            field=models.TextField(default='', max_length=100),
        ),
    ]
