# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20161206_0306'),
        ('reports', '0009_reportfile_rhash'),
    ]

    operations = [
    ]
