# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('tstamp', models.DateTimeField(auto_now=True)),
                ('short', models.CharField(blank=True, max_length=50, verbose_name='Short Description')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Summary')),
                ('owners', models.ManyToManyField(related_name='owners', through='reports.Ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfile', models.FileField(upload_to=b'')),
                ('reports', models.ManyToManyField(through='reports.Fileship', to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Viewership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', through='reports.Viewership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownership',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileship',
            name='repfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportFile'),
        ),
        migrations.AddField(
            model_name='fileship',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
