# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('name', models.TextField()),
                ('fileCont', models.TextField()),
            ],
        ),
    ]
