# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_priv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='rfile',
            field=models.FileField(upload_to=''),
        ),
    ]
