# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_priv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='rfile',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='name',
            field=models.CharField(default='default', max_length=30, unique=True),
        ),
    ]
