# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20161127_0407'),
        ('reports', '0004_auto_20161126_1824'),
    ]

    operations = [
    ]
