# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500)),
                ('etext', models.BinaryField(blank=True)),
                ('sender', models.CharField(blank=True, max_length=50)),
                ('recipient', models.CharField(blank=True, max_length=50)),
                ('encrypted', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
