# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500)),
                ('sender', models.TextField(blank=True, max_length=500)),
                ('recipient', models.TextField(blank=True, max_length=500)),
                ('encryptedFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
